apiVersion: apps/v1
kind: Deployment
metadata:
  name: commitm2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commitm2
  template:
    metadata:
      labels:
        app: commitm2
    spec:
      containers:
      - name: commitm2
        image: commitm2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080" # Listen on all network interfaces
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"          # Optional, for logging behavior
        - name: DOTNET_HOST_PATH
          value: "/usr/share/dotnet" # Optional, only needed if using volumes
