apiVersion: v1
kind: Service
metadata:
  name: commitm2-service
spec:
  type: NodePort
  selector:
    app: commitm2
  ports:
  - protocol: TCP
    port: 8080         # puerto interno del pod (donde escucha la API)
    targetPort: 8080   # debe coincidir con containerPort
    nodePort: 30080    # acceso externo desde localhost:30080
